Repository bold-commerce/adobe-commerce-bold-checkout-payment-booster, pull requests merged in 2024-12, with the labels that each got.

#132 CHK-6522: If configuration group is empty default to the store domain
  Model/CheckoutData.php
  Model/Eps/GetFastlaneStyles.php
  UI/PaymentBoosterConfigProvider.php
  etc/adminhtml/system.xml
Labels: enhancement

#136 CHK-6522: Make Configuration Group Label setting optional
  etc/adminhtml/system.xml
Labels: bug

#137 CHK-6795: Update composer version number to 2.2.6
  composer.json
Labels: release

#135 CHK-6773: Validate Agreements Before Render
  view/frontend/web/js/model/spi.js
Labels: bug

#138 [CHK-4370] Enable GPAY PPCP Express Checkout
  view/frontend/web/js/action/express-pay/update-quote-shipping-method-action.js
Labels: enhancement

#133 EPS-170: Add loading section for wallet pays
  view/frontend/web/css/source/_module.less
  view/frontend/web/js/view/bold-express-pay.js
  view/frontend/web/template/express-pay.html
Labels: enhancement

#140 [CHK-6462] Enable Google Pay Button on Payment Step
  view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js
  view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: enhancement

#141 CHK-6821: Fix Place Order Error When Agreements Are Not Accepted
  view/frontend/web/js/model/spi.js
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#148 CHK-6924: Don't remove www. prefix from configuration group label
  Model/Eps/GetFastlaneStyles.php
  UI/PaymentBoosterConfigProvider.php
Labels: bug

#146 [CHK-6869] Remove Prototype Import to Prevent JS Dump
  view/frontend/web/js/action/express-pay/update-quote-shipping-method-action.js
  view/frontend/web/js/model/fastlane.js
Labels: bug

#134 Add express pay to cart & mini-cart
  Block/ShortcutButtons/ExpressPayShortcutButtons.php
  CustomerData/BoldCheckoutData.php
  Model/CheckoutData.php
  Model/InitOrderFromQuote.php
  Observer/Checkout/InitializeBoldOrderObserver.php
  Observer/ShortcutButtons/AddExpressPayButtonsObserver.php
  Plugin/Framework/App/FrontControllerPlugin.php
  UI/PaymentBoosterConfigProvider.php
  ViewModel/ExpressPay.php
  composer.json
  etc/frontend/di.xml
  etc/frontend/events.xml
  etc/frontend/sections.xml
  etc/module.xml
  view/frontend/layout/checkout_cart_index.xml
  view/frontend/templates/express-pay.phtml
  view/frontend/web/js/action/express-pay/update-quote-address-action.js
  view/frontend/web/js/action/express-pay/update-quote-shipping-method-action.js
  view/frontend/web/js/express-pay-storefront.js
  view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
  view/frontend/web/js/model/spi/callbacks/on-create-payment-order-callback.js
Labels: enhancement

#152 CHK-6986 release version 2.2.8
  composer.json
Labels: release

#150 CHK-6262: Update address on approve payment for wallet pays
  view/frontend/web/js/action/express-pay/update-quote-address-action.js
  view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js
  view/frontend/web/js/action/express-pay/update-quote-wallet-pay-action.js
  view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
Labels: bug

#153 CHK-6308: Fix incomplete shipping address with Braintree Apple/Google Pay
  view/frontend/web/js/action/express-pay/update-quote-wallet-pay-action.js
  view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
Labels: bug
