Repository bold-commerce/adobe-commerce-bold-checkout-payment-booster, pull requests merged in 2024-11, with the labels that each got.

#113 CHK-6312: Fix errors thrown for prices greater than 1000
  Service/ExpressPay/QuoteConverter.php
Labels: bug

#115 CHK-4371: Add name and phone number to quote converter test data
  Test/Integration/Service/ExpressPay/QuoteConverterTest.php
Labels: bug

#124 CHK-6470: Update composer version number to 2.2.3
  composer.json
Labels: release

#118 CHK-5478: Update CODEOWNERS
  .github/CODEOWNERS
Labels: developer-experience

#127 [CHK-6741] Update Composer Version Number to 2.2.4
  composer.json
Labels: release
