Repository bold-commerce/adobe-commerce-bold-checkout-payment-booster, pull requests merged in 2025-03, with the labels that each got.

#226 [CHK-7948] Set correct totals for paylater messaging on product page
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
Labels: bug

#223 CHK-7721 - add public_order_id to PayPal create order request
  Service/ExpressPay/Order/Create.php
  Test/Integration/Service/ExpressPay/Order/CreateTest.php
  view/frontend/web/js/action/express-pay/create-wallet-pay-order-action.js
Labels: developer-experience

#227 CHK-7994: Revert Pull Request 215
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
Labels: reversion

#228 CHK-7993: Revert Pull Request 218
  Controller/Digitalwallets/Quote/Deactivate.php
  Service/DigitalWallets/MagentoQuote/Deactivator.php
  Test/Integration/Controller/Digitalwallets/Quote/DeactivateTest.php
  Test/Integration/Service/DigitalWallets/MagentoQuote/DeactivatorTest.php
  view/frontend/web/js/action/digital-wallets/deactivate-quote.js
  view/frontend/web/js/model/spi.js
Labels: reversion

#229 CHK-7992: Revert Pull Request 212
  Plugin/Framework/App/ActionInterfacePlugin.php
  Test/Integration/Plugin/Framework/App/ActionInterfacePluginTest.php
  ViewModel/ExpressPay.php
  etc/di.xml
  etc/frontend/di.xml
Labels: reversion

#230 CHK-7991: Revert Pull Request 209
  Plugin/Framework/App/FrontControllerPlugin.php
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
  view/frontend/web/js/express-pay-storefront.js
Labels: reversion

#231 CHK-7996: Revert Pull Request 226
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
Labels: reversion

#233 CHK-7990: Revert Pull Request 204
  Api/Data/MagentoQuoteBoldOrderInterface.php
  Api/MagentoQuoteBoldOrderRepositoryInterface.php
  Controller/Digitalwallets/Quote/Create.php
  Model/Config.php
  Model/MagentoQuoteBoldOrder.php
  Model/MagentoQuoteBoldOrderRepository.php
  Model/ResourceModel/MagentoQuoteBoldOrder.php
  Observer/Order/BeforePlaceObserver.php
  Plugin/Payment/Model/Checks/CanUseCheckoutPlugin.php
  Plugin/Quote/Api/CartRepositoryInterfacePlugin.php
  Service/DigitalWallets/MagentoQuote/Creator.php
  Service/DigitalWallets/MagentoQuote/TotalsRetriever.php
  Test/Integration/Controller/Digitalwallets/Quote/CreateTest.php
  Test/Integration/Plugin/Payment/Model/Checks/CanUseCheckoutPluginTest.php
  Test/Integration/Plugin/Quote/Api/CartRepositoryInterfacePluginTest.php
  Test/Integration/Service/DigitalWallets/MagentoQuote/CreatorTest.php
  Test/Integration/Service/DigitalWallets/MagentoQuote/TotalsRetrieverTest.php
  Test/Integration/_Assertions/AssertPluginIsConfiguredCorrectly.php
  Test/Integration/_files/magento_quote_bold_order.php
  Test/Integration/_files/magento_quote_bold_order_rollback.php
  UI/PaymentBoosterConfigProvider.php
  composer.json
  etc/adminhtml/system.xml
  etc/db_schema.xml
  etc/db_schema_whitelist.json
  etc/di.xml
  etc/extension_attributes.xml
  etc/frontend/di.xml
  etc/frontend/routes.xml
  etc/module.xml
  etc/webapi_rest/di.xml
  view/frontend/web/js/action/digital-wallets/create-quote.js
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
  view/frontend/web/js/model/spi.js
  view/frontend/web/js/model/spi/callbacks/on-click-payment-order-callback.js
Labels: reversion

#234 CHK-7998: Revert Pull Request 233
  Api/Data/MagentoQuoteBoldOrderInterface.php
  Api/MagentoQuoteBoldOrderRepositoryInterface.php
  Controller/Digitalwallets/Quote/Create.php
  Model/Config.php
  Model/MagentoQuoteBoldOrder.php
  Model/MagentoQuoteBoldOrderRepository.php
  Model/ResourceModel/MagentoQuoteBoldOrder.php
  Observer/Order/BeforePlaceObserver.php
  Plugin/Payment/Model/Checks/CanUseCheckoutPlugin.php
  Plugin/Quote/Api/CartRepositoryInterfacePlugin.php
  Service/DigitalWallets/MagentoQuote/Creator.php
  Service/DigitalWallets/MagentoQuote/TotalsRetriever.php
  Test/Integration/Controller/Digitalwallets/Quote/CreateTest.php
  Test/Integration/Plugin/Payment/Model/Checks/CanUseCheckoutPluginTest.php
  Test/Integration/Plugin/Quote/Api/CartRepositoryInterfacePluginTest.php
  Test/Integration/Service/DigitalWallets/MagentoQuote/CreatorTest.php
  Test/Integration/Service/DigitalWallets/MagentoQuote/TotalsRetrieverTest.php
  Test/Integration/_Assertions/AssertPluginIsConfiguredCorrectly.php
  Test/Integration/_files/magento_quote_bold_order.php
  Test/Integration/_files/magento_quote_bold_order_rollback.php
  UI/PaymentBoosterConfigProvider.php
  composer.json
  etc/adminhtml/system.xml
  etc/db_schema.xml
  etc/db_schema_whitelist.json
  etc/di.xml
  etc/extension_attributes.xml
  etc/frontend/di.xml
  etc/frontend/routes.xml
  etc/module.xml
  etc/webapi_rest/di.xml
  view/frontend/web/js/action/digital-wallets/create-quote.js
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
  view/frontend/web/js/model/spi.js
  view/frontend/web/js/model/spi/callbacks/on-click-payment-order-callback.js
Labels: reversion

#235 CHK-7999: Revert Pull Request 230
  Plugin/Framework/App/FrontControllerPlugin.php
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
  view/frontend/web/js/express-pay-storefront.js
Labels: reversion

#236 CHK-8000: Revert Pull Request 229
  Plugin/Framework/App/ActionInterfacePlugin.php
  Test/Integration/Plugin/Framework/App/ActionInterfacePluginTest.php
  ViewModel/ExpressPay.php
  etc/di.xml
  etc/frontend/di.xml
Labels: reversion

#237 CHK-8001: Revert Pull Request 228
  Controller/Digitalwallets/Quote/Deactivate.php
  Service/DigitalWallets/MagentoQuote/Deactivator.php
  Test/Integration/Controller/Digitalwallets/Quote/DeactivateTest.php
  Test/Integration/Service/DigitalWallets/MagentoQuote/DeactivatorTest.php
  view/frontend/web/js/action/digital-wallets/deactivate-quote.js
  view/frontend/web/js/model/spi.js
Labels: reversion

#239 CHK-8003: Revert Pull Request 231
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
Labels: reversion

#241 CHK-7812: Release Version 2.4.3
  composer.json
Labels: release

#244 CHK-7953: Fix Errors for Authenticated Customers When Paying via Digital Wallets
  Observer/ShortcutButtons/AddExpressPayButtonsObserver.php
  ViewModel/ExpressPay.php
  view/frontend/templates/express-pay-minicart.phtml
  view/frontend/templates/express-pay-product.phtml
Labels: bug

#247 CHK-8030: Secure Get Bold Config AJAX Endpoint With Form Key
  Controller/Digitalwallets/Checkout/GetConfig.php
  view/frontend/web/js/express-pay-storefront.js
Labels: enhancement, security

#232 INFRA-2569: Implement Workflow For Verifying Code Quality
  .github/workflows/pull-request-job.yml
  .phpcs.xml
  composer.json
  phpstan.neon
Labels: developer-experience, infrastructure

#250 CHK-8046: Revert Pull Requests 205 & 213
  Plugin/ReCaptcha/Model/DisableRecaptchaForExpressPayPlugin.php
  Service/ExpressPay/Callback/OnApprove.php
  etc/di.xml
  etc/webapi.xml
  view/frontend/web/js/action/express-pay/on-approve-express-pay-order-action.js
  view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
Labels: bug, reversion

#249 CHK-8045: Release Version 2.4.4
  composer.json
Labels: release

#251 CHK-8035 - render Place Order button for credit card gateways
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#245 CHK-7964 Support GDPR checkboxes on cart and express checkout
  composer.json
  etc/module.xml
  view/frontend/requirejs-config.js
  view/frontend/web/js/model/agreements-assigner-mixin.js
  view/frontend/web/js/model/customer-email-validator-mixin.js
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: enhancement

#253 CHK-8083: Fix Inability To Place Order From Credit Card Form in Checkout
  view/frontend/web/js/mixin/payment-default-mixin.js
Labels: bug

#252 CHK-7857: Prevent Reuse of Bold Public Order ID
  Api/Data/MagentoQuoteBoldOrderInterface.php
  Api/MagentoQuoteBoldOrderRepositoryInterface.php
  Controller/Digitalwallets/Checkout/GetPaymentGateways.php
  Model/MagentoQuoteBoldOrderRepository.php
  Observer/Order/AfterSubmitObserver.php
  Plugin/Booster/Service/DigitalWallets/MagentoQuote/CreatorPlugin.php
  Test/Integration/Controller/Digitalwallets/Checkout/GetPaymentGatewaysTest.php
  Test/Integration/Plugin/Booster/Service/DigitalWallets/MagentoQuote/CreatorPluginTest.php
  etc/frontend/di.xml
  view/frontend/web/js/action/digital-wallets/get-payment-gateways.js
  view/frontend/web/js/model/spi/callbacks/on-click-payment-order-callback.js
Labels: bug

#221 INFRA-2249: Create GitHub Actions Workflow To Automatically Run Integration Tests
  .github/workflows/pull-request-integration-tests-job.yml
  Test/Integration/Service/ExpressPay/QuoteConverterTest.php
  integration-pipeline-test/install-config-mysql-ci-2.4.3-p3.php
  integration-pipeline-test/install-config-mysql-ci-2.4.7-p4.php
Labels: developer-experience, infrastructure

#256 CHK-8104: Update CODEOWNERS
  .github/CODEOWNERS
Labels: developer-experience, infrastructure

#257 CHK-8034: Disable Place Order Button on Payment Step of Checkout If No Billing Address Is Entered
  view/frontend/web/template/payment/spi.html
Labels: bug

#258 CHK-8124: Fix SOAP and Swagger API Errors
  Api/Data/Order/Payment/PaymentInterface.php
  Api/ExpressPay/Order/CreateInterface.php
  Api/ExpressPay/Order/GetInterface.php
  Api/ExpressPay/Order/UpdateInterface.php
  Service/ExpressPay/Order/Create.php
  Service/ExpressPay/Order/Get.php
  Service/ExpressPay/Order/Update.php
  etc/di.xml
  etc/webapi.xml
Labels: bug

#259 CHK-8134: Release Version 2.5.1
  composer.json
Labels: release

#261 CHK-8183: Ensure EPS SDK is Rendered Only Once
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#260 CHK-7757: Automatically Clean Up Old Active Digital Wallets Quotes
  .github/workflows/pull-request-integration-tests-job.yml
  Cron/DigitalWallets/DeactivateQuotes.php
  Model/Config/Backend/DigitalWallets/DeactivateQuotes.php
  Model/Config/Source/Frequency.php
  Service/DigitalWallets/MagentoQuote/Deactivator.php
  Test/Integration/Cron/DigitalWallets/DeactivateQuotesTest.php
  Test/Integration/Model/Config/Backend/DigitalWallets/DeactivateQuotesTest.php
  Test/Integration/Service/DigitalWallets/MagentoQuote/DeactivatorTest.php
  Test/Integration/_Stubs/Magento/Quote/Model/ResourceModel/Quote/CollectionStub.php
  Test/Integration/_files/multiple_active_digital_wallets_quotes.php
  Test/Integration/_files/multiple_active_digital_wallets_quotes_rollback.php
  composer.json
  etc/adminhtml/system.xml
  etc/config.xml
  etc/crontab.xml
  etc/di.xml
  etc/module.xml
Labels: enhancement

#262 CHK-8082: Prevent Clearing Quote From Session After Placing Digital Wallets Order
  Plugin/Checkout/Model/SessionPlugin.php
  Test/Integration/Plugin/Checkout/Model/SessionPluginTest.php
  Test/Integration/_files/digital_wallets_quote.php
  Test/Integration/_files/digital_wallets_quote_rollback.php
  etc/frontend/di.xml
Labels: enhancement

#263 CHK-8187: Fix Database Schema Error in Adobe Commerce 2.3
  patches/Fix_bold_booster_magento_quote_bold_order_Schema-2.3.x.patch
Labels: bug

#264 CHK-7757: Add Missing Dependency to Retention Period Configuration Field
  etc/adminhtml/system.xml
Labels: bug

#266 CHK-8203: Release Version 2.5.2
  composer.json
Labels: release

#267 CHK-8176: Declare Missing Dependencies
  composer.json
  etc/module.xml
Labels: bug

#269 CHK-8217: Fix Indefinite Loading on 3D Secure Authentication Page
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#272 CHK-8217: Fix Indefinite Loading on 3D Secure Authentication Page
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#273 CHK-8260: Release Version v2.5.3
  composer.json
Labels: release
