Repository bold-commerce/adobe-commerce-bold-checkout-payment-booster, pull requests merged in 2025-01, with the labels that each got.

#160 [CHK-7028] Add google pay button to wallet pay options when fastlane enabled
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: enhancement

#163 CHK-7004: Revert PR #156
  Service/ExpressPay/QuoteConverter.php
Labels: reversion

#151 CHK-6928: Provide Page Source as Option to EPS Payments SDK
  Observer/ShortcutButtons/AddExpressPayButtonsObserver.php
  UI/PaymentBoosterConfigProvider.php
  view/frontend/layout/catalog_product_view.xml
  view/frontend/layout/catalog_product_view_type_bundle.xml
  view/frontend/layout/checkout_cart_index.xml
  view/frontend/layout/checkout_index_index.xml
  view/frontend/templates/express-pay.phtml
  view/frontend/web/js/express-pay-storefront.js
  view/frontend/web/js/model/spi/callbacks/on-click-payment-order-callback.js
  view/frontend/web/js/view/bold-express-pay.js
Labels: enhancement

#165 [CHK-6967] Add missing window data for auth customers
  ViewModel/ExpressPay.php
  view/frontend/templates/express-pay.phtml
Labels: bug

#166 [CHK-7008] Update admin express pay verbiage to 'Digital Wallets'
  etc/adminhtml/system.xml
Labels: marketing

#168 [CHK-7145] Fix Quote Initialization for Apple Pay on Product Detail Page
  Api/Quote/GetQuoteInterface.php
  Model/Config.php
  Service/Quote/GetQuote.php
  etc/webapi.xml
  view/frontend/web/js/action/express-pay/add-product-to-cart-action.js
  view/frontend/web/js/action/express-pay/get-active-quote-action.js
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
  view/frontend/web/js/model/spi.js
  view/frontend/web/js/model/spi/callbacks/on-click-payment-order-callback.js
Labels: bug

#167 [CHK-7163] Fix mini-cart digital wallets purchasing wrong item on PDP
  UI/PaymentBoosterConfigProvider.php
  ViewModel/ExpressPay.php
  view/frontend/templates/express-pay.phtml
  view/frontend/web/js/express-pay-storefront.js
  view/frontend/web/js/model/spi.js
Labels: bug

#170 [CHK-7198] Fix PayPal in Mini-cart for Auth users
  view/frontend/templates/express-pay.phtml
Labels: bug

#161 CHK-4774 Add error message for invalid CC details in SPI
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#172 Release version 2.2.11
  composer.json
Labels: release

#162 CHK-6966: Don't update address when not express pay
  view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
  view/frontend/web/js/model/spi/callbacks/on-create-payment-order-callback.js
Labels: bug

#178 CHK-7314: Release version 2.2.12
  composer.json
Labels: release

#155 CHK-6833 fixing the Place Order button showing error
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#180 CHK-7466: Release Version 2.2.13
  composer.json
Labels: release

#173 CHK-6987 Fixing the Amasty GDPR module checkboxes validation
  view/frontend/web/js/model/spi.js
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#181 CHK-7467 release 2.2.14
  composer.json
Labels: release

#182 CHK-7483: Non Express wallet pay shipping data
  view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js
Labels: bug

#183 CHK-7520: Implement Digital Wallets in Cart and Mini Cart
  Block/ShortcutButtons/ExpressPayShortcutButtons.php
  CustomerData/BoldCheckoutData.php
  Model/CheckoutData.php
  Model/Config.php
  Model/InitOrderFromQuote.php
  Observer/Checkout/InitializeBoldOrderObserver.php
  Observer/ShortcutButtons/AddExpressPayButtonsObserver.php
  Plugin/Framework/App/FrontControllerPlugin.php
  Service/ExpressPay/Order/Create.php
  Service/ExpressPay/Order/Update.php
  UI/PaymentBoosterConfigProvider.php
  ViewModel/ExpressPay.php
  composer.json
  etc/adminhtml/system.xml
  etc/config.xml
  etc/di.xml
  etc/frontend/di.xml
  etc/frontend/events.xml
  etc/frontend/sections.xml
  etc/module.xml
  view/frontend/layout/checkout_index_index.xml
  view/frontend/templates/express-pay.phtml
  view/frontend/web/js/action/express-pay/create-wallet-pay-order-action.js
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
  view/frontend/web/js/action/express-pay/update-quote-address-action.js
  view/frontend/web/js/action/express-pay/update-quote-shipping-method-action.js
  view/frontend/web/js/express-pay-storefront.js
  view/frontend/web/js/model/spi.js
  view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
  view/frontend/web/js/model/spi/callbacks/on-create-payment-order-callback.js
  view/frontend/web/js/view/bold-express-pay.js
Labels: enhancement

#186 [CHK-7528] Reset paymentId on placeOrderClick
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#187 [CHK-7543] Release Version 2.3.1
  composer.json
Labels: release

#188 CHK-7553: Fix Error Preventing Stripe Credit Card Form From Loading
  view/frontend/web/js/model/spi.js
Labels: bug

#189 CHK-7565: Hide Enable Digital Wallets on Cart Page setting when Payment Booster is disabled
  etc/adminhtml/system.xml
Labels: bug
