Repository bold-commerce/adobe-commerce-bold-checkout-payment-booster, pull requests merged in 2025-02, with the labels that each got.

#190 CHK-7544: Create capture when receiving capture result from checkout
  Api/Data/Order/Payment/PaymentInterface.php
  Api/Data/Order/Payment/TransactionInterface.php
  Api/Order/UpdatePaymentsInterface.php
  Model/Order/Payment.php
  Model/Order/Transaction.php
  Model/Order/UpdatePayments.php
  Model/Order/UpdatePayments/CreateInvoice.php
  etc/di.xml
Labels: enhancement

#185 CHK-7148: Fix Issue With Tax-Inclusive Products and Add Allowed Countries to renderPayments
  Model/Config.php
  UI/PaymentBoosterConfigProvider.php
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#191 [CHK-7183] Remove extra calls to hydrate endpoint
  view/frontend/web/js/action/general/hydrate-order-action.js
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
Labels: bug

#192 CHK-7625: Release Version v2.3.2
  composer.json
Labels: release

#177 EPS-169: Create New Wallet Payments Payment Method
  Model/Config.php
  Model/Payment/Gateway/Service.php
  Plugin/Quote/Model/QuoteManagement/DisableBoldAddressValidationPlugin.php
  UI/Payment/WalletPaymentsConfigProvider.php
  etc/adminhtml/system.xml
  etc/config.xml
  etc/di.xml
  etc/frontend/di.xml
  etc/payment.xml
  view/frontend/layout/checkout_index_index.xml
  view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
  view/frontend/web/js/view/payment/bold-payments.js
  view/frontend/web/js/view/payment/method-renderer/bold-spi.js
  view/frontend/web/js/view/payment/method-renderer/bold-wallet-payments.js
  view/frontend/web/template/payment/wallet-payments.html
Labels: enhancement

#193 [CHK-7418] - Fix missing phone number on addresses
  view/frontend/web/js/action/express-pay/update-quote-address-action.js
  view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js
Labels: bug

#194 [CHK-7647] Release Version 2.4.0
  composer.json
Labels: release

#197 CHK-7563: Fix wrong billing address for wallet pay buttons at payment step
  view/frontend/web/js/action/express-pay/update-quote-braintree-action.js
  view/frontend/web/js/action/express-pay/update-quote-ppcp-action.js
  view/frontend/web/js/action/express-pay/update-quote-wallet-pay-action.js
  view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
Labels: bug

#200 CHK-7711: Hide configuration on default scope and add throw error if shop_id is not configured in init
  Model/CheckoutData.php
  etc/adminhtml/system.xml
Labels: bug

#203 CHK-7737: Update version number to 2.4.1
  composer.json
Labels: release

#206 [CHK-6948] Fix paypal modal when shop doesn't ship to selected address
  view/frontend/web/js/action/express-pay/save-shipping-information-action.js
Labels: bug

#208 [CHK-7770] Increase version number to 2.4.2
  composer.json
Labels: release

#195 CHK-7114: Support compatibility with Multi-currency extensions
  Service/ExpressPay/QuoteConverter.php
  Test/Integration/Service/ExpressPay/QuoteConverterTest.php
  Test/Integration/_files/quote_non_base_currency.php
Labels: bug

#204 CHK-7504: Implement Digital Wallets on Product Detail Page
  Api/Data/MagentoQuoteBoldOrderInterface.php
  Api/MagentoQuoteBoldOrderRepositoryInterface.php
  Controller/Digitalwallets/Quote/Create.php
  Model/Config.php
  Model/MagentoQuoteBoldOrder.php
  Model/MagentoQuoteBoldOrderRepository.php
  Model/ResourceModel/MagentoQuoteBoldOrder.php
  Observer/Order/BeforePlaceObserver.php
  Plugin/Payment/Model/Checks/CanUseCheckoutPlugin.php
  Plugin/Quote/Api/CartRepositoryInterfacePlugin.php
  Service/DigitalWallets/MagentoQuote/Creator.php
  Service/DigitalWallets/MagentoQuote/TotalsRetriever.php
  Test/Integration/Controller/Digitalwallets/Quote/CreateTest.php
  Test/Integration/Plugin/Payment/Model/Checks/CanUseCheckoutPluginTest.php
  Test/Integration/Plugin/Quote/Api/CartRepositoryInterfacePluginTest.php
  Test/Integration/Service/DigitalWallets/MagentoQuote/CreatorTest.php
  Test/Integration/Service/DigitalWallets/MagentoQuote/TotalsRetrieverTest.php
  Test/Integration/_Assertions/AssertPluginIsConfiguredCorrectly.php
  Test/Integration/_files/magento_quote_bold_order.php
  Test/Integration/_files/magento_quote_bold_order_rollback.php
  UI/PaymentBoosterConfigProvider.php
  composer.json
  etc/adminhtml/system.xml
  etc/db_schema.xml
  etc/db_schema_whitelist.json
  etc/di.xml
  etc/extension_attributes.xml
  etc/frontend/di.xml
  etc/frontend/routes.xml
  etc/module.xml
  etc/webapi_rest/di.xml
  view/frontend/web/js/action/digital-wallets/create-quote.js
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
  view/frontend/web/js/model/spi.js
  view/frontend/web/js/model/spi/callbacks/on-click-payment-order-callback.js
Labels: enhancement

#205 CHK-7315 - fix Express Pay multiple authorizations when ReCaptcha fails
  Plugin/ReCaptcha/DisableRecaptchaForExpressPayPlugin.php
  Service/ExpressPay/Callback/OnApprove.php
  etc/di.xml
  etc/webapi.xml
  view/frontend/web/js/action/express-pay/on-approve-express-pay-order-action.js
  view/frontend/web/js/model/spi/callbacks/on-approve-payment-order-callback.js
Labels: bug

#214 CHK-7256: Add Bold local env domain to style-src CSP whitelist
  etc/csp_whitelist.xml
Labels: developer-experience

#213 CHK-7818 - fix namespace for DisableRecaptchaForExpressPayPlugin.php
  Plugin/ReCaptcha/Model/DisableRecaptchaForExpressPayPlugin.php
Labels: bug

#209 CHK-7780: Fix Errors Thrown by Digital Wallets in Mini Cart on Product Detail Page
  Plugin/Framework/App/FrontControllerPlugin.php
  view/frontend/web/js/action/express-pay/get-required-order-data-action.js
  view/frontend/web/js/express-pay-storefront.js
Labels: bug

#212 CHK-7784: Fix Digital Wallets Not Working on Product Page for Logged-in Customers
  Plugin/Framework/App/ActionInterfacePlugin.php
  Test/Integration/Plugin/Framework/App/ActionInterfacePluginTest.php
  ViewModel/ExpressPay.php
  etc/di.xml
  etc/frontend/di.xml
Labels: bug

#202 CHK-6927: Fix Incorrect Item Total Sent To Checkout API When Prices Include Tax
  Service/ExpressPay/QuoteConverter.php
Labels: bug

#196 CHK-7629: Update CSP Whitelist for 2.4.x Versions and Add Compatibility Patch for 2.3.x Versions
  PATCHES.md
  etc/csp_whitelist.xml
  patches/MAGETWO-PAYMENT-BOOSTER_2.3.x.patch
Labels: bug

#219 CHK-7921: Resolve rounding issues
  Service/ExpressPay/QuoteConverter.php
Labels: bug

#218 CHK-7756: Deactivate Digital Wallets Quote on Error or Cancellation
  Controller/Digitalwallets/Quote/Deactivate.php
  Service/DigitalWallets/MagentoQuote/Deactivator.php
  Test/Integration/Controller/Digitalwallets/Quote/DeactivateTest.php
  Test/Integration/Service/DigitalWallets/MagentoQuote/DeactivatorTest.php
  view/frontend/web/js/action/digital-wallets/deactivate-quote.js
  view/frontend/web/js/model/spi.js
Labels: enhancement

#176 [CHK-7161] Adobe Commerce: Remove "Added to cart" alert on checkout success page
  Observer/Product/ExpressPayAfterAddToCartObserver.php
  etc/frontend/events.xml
Labels: bug

#217 CHK-7629: Add csp_whitelist.xml patch for composer version
  PATCHES.md
  patches/CSP-PAYMENT-BOOSTER_2.3.x.patch
  patches/CSP-PAYMENT-BOOSTER_COMPOSER_2.3.x.patch
Labels: enhancement
